Serilog:
  Using:
    - Serilog.Sinks.Console
    - Serilog.Sinks.File
  MinimumLevel: Debug
  WriteTo:
    - Name: Console
    - Name: File
      Args:
        path: "logs/log-.txt"
        rollingInterval: Day
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
  Enrich:
    - FromLogContext
    - WithMachineName