# Server
# 服务器监听
Listen : "http://127.0.0.1:9944/"
# 节点池
# Node Pool
Nodes:
  - Name: "seattle"
    Url: "ws://seattle.gemini-3h.subspace.edgeone.net"
    Pools: 
      - Piece
  - Name: "kiangsu"
    Url: "ws://kiangsu.gemini-3h.subspace.edgeone.net"
    Pools: 
      - Submit