# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build win-x64
      run: dotnet publish Subspace.Agent -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Compress Build Win-x64 Artifact
      run: zip -r win-x64.zip /home/runner/work/Subspace.Agent/Subspace.Agent/Subspace.Agent/bin/Release/net8.0/win-x64/publish
      working-directory: /home/runner/work/Subspace.Agent/Subspace.Agent/Subspace.Agent/bin/Release/net8.0/win-x64/publish
    - name: Upload Release Win-x64 Asset
      id: upload-release-win-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/work/Subspace.Agent/Subspace.Agent/Subspace.Agent/bin/Release/net8.0/win-x64/publish/win-x64.zip
        asset_name: win-x64.zip
        asset_content_type: application/zip
      
    - name: Build linux-x64
      run: dotnet publish Subspace.Agent -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Compress Build Linux-x64 Artifact
      run: zip -r linux-x64.zip /home/runner/work/Subspace.Agent/Subspace.Agent/Subspace.Agent/bin/Release/net8.0/linux-x64/publish
      working-directory: /home/runner/work/Subspace.Agent/Subspace.Agent/Subspace.Agent/bin/Release/net8.0/linux-x64/publish
    - name: Upload Release Linux-x64 Asset
      id: upload-release-linux-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/work/Subspace.Agent/Subspace.Agent/Subspace.Agent/bin/Release/net8.0/linux-x64/publish/linux-x64.zip
        asset_name: linux-x64.zip
        asset_content_type: application/zip

    - name: Test
      run: dotnet test --no-build --verbosity normal
